"""add report deadline and reminder log

Revision ID: 2dc5376b4f64
Revises: cc0c09881608
Create Date: 2026-08-29 23:28:06.960974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc5376b4f64'
down_revision: Union[str, None] = 'cc0c09881608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_logs_event_key'), ['event_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_reminder_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_deadline_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('report_deadline_time')
        batch_op.drop_column('report_weekday')

    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_logs_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_logs_event_key'))

    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
