"""add defense_date to projects

Revision ID: 5fde7409659f
Revises: 52cfa7ab7a7c
Create Date: 2026-08-23 02:32:08.902849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fde7409659f'
down_revision: Union[str, None] = '52cfa7ab7a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('defense_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'defense_date')
    # ### end Alembic commands ###
