"""add defense outcome and meeting requests

Revision ID: 7dfd57ac184e
Revises: 2dc5376b4f64
Create Date: 2026-08-30 00:14:17.458939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfd57ac184e'
down_revision: Union[str, None] = '2dc5376b4f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_requests_id'), ['id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defense_outcome', sa.Enum('PASS_', 'NEEDS_REVISION', 'FAIL', name='defenseoutcome'), nullable=True))
        batch_op.add_column(sa.Column('defense_outcome_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('defense_outcome_notes')
        batch_op.drop_column('defense_outcome')

    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_requests_id'))

    op.drop_table('meeting_requests')
    # ### end Alembic commands ###
